// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

namespace Persistence.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210113172800_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0");

            modelBuilder.Entity("Domain.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumberOfProducts")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PriceEa")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProductName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            NumberOfProducts = 200,
                            PriceEa = 3,
                            ProductName = "paczki"
                        },
                        new
                        {
                            Id = 2,
                            NumberOfProducts = 1000,
                            PriceEa = 2,
                            ProductName = "gwozdzie"
                        },
                        new
                        {
                            Id = 3,
                            NumberOfProducts = 10000,
                            PriceEa = 1,
                            ProductName = "cukierki"
                        },
                        new
                        {
                            Id = 4,
                            NumberOfProducts = 100,
                            PriceEa = 300,
                            ProductName = "wiertarki"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
